"use client";

import type { Metadata } from "next";
import { useEffect } from "react";
import "./globals.css";
import { motion, useScroll } from "framer-motion";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { scrollYProgress } = useScroll();

  useEffect(() => {
    console.log(scrollYProgress);
  }, [scrollYProgress]);

  return (
    <html lang="en">
      <body
        className={`bg-background text-gray-400 scrollbar-thin scrollbar-w-[5px]  scrollbar-thumb-primary scrollbar-track-muted overflow-x-hidden`}
      >
        <motion.div
          className="fixed z-10 top-0 inset-x-0 h-[7px] origin-[0%] bg-primary"
          style={{ scaleX: scrollYProgress }}
        />
        <div className="pt-[7px]">
          <Navbar />
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
